It's time to revisit your classifier from the previous assignment. Using the evaluation techniques we've covered here, look at your classifier's performance in more detail. Then go back and iterate by engineering new features, removing poor features, or tuning parameters. Repeat this process until you have five different versions of your classifier. Once you've iterated, answer these questions to compare the performance of each:

Do any of your classifiers seem to overfit?
Which seem to perform the best? Why?
Which features seemed to be most impactful to performance?
Write up your iterations and answers to the above questions in a few pages. Submit a link below and go over it with your mentor to see if they have any other ideas on how you could improve your classifier's performance.

In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import BernoulliNB
from sklearn.metrics import confusion_matrix

reviews = pd.read_csv('amazon_cells_labelled.txt', delimiter='\t', header=None)
reviews.columns = ['review', 'sentiment']

In [2]:
keywords = ['good', 'great', 'excellent', 'awesome','love', 'loves', 'nice','recommend', 'must have','nice', 'beautiful', 'super', 'best']



In [3]:
data = reviews[keywords]
target = reviews['sentiment']
X_train, X_test, y_train, y_test = train_test_split(data, target, test_size=0.2, random_state=20)

In [7]:
bnb = BernoulliNB()


array([0.64, 0.63, 0.64, 0.59, 0.61, 0.6 , 0.61, 0.61, 0.64, 0.55])

In [72]:
## Loop removing 3 keywords in 5 iterations to measure importance of each word

keywords = ['good', 'great', 'excellent', 'awesome','love', 'loves', 'nice','recommend', 'must have','nice', 'beautiful', 'super', 'best']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    reviews[str(key)] = reviews.review.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

cv=[]
cv_mean=[]
cv_std=[]
conf=[]
correct=[]
wrong=[]

for i in range(5):
    
    del reviews[keywords[0]] 
    del reviews[keywords[1]]
    del reviews[keywords[2]]
    
    del keywords[0:2]
    print(keywords)
    
    for key in keywords:
        # Note that we add spaces around the key so that we're getting the word,
        # not just pattern matching.
        reviews[str(key)] = reviews.review.str.contains(
            ' ' + str(key) + ' ',
            case=False
        )

    data = reviews[keywords]
    target = reviews['sentiment']
    
    bnb.fit(data, target)
    y_pred = bnb.predict(data)
    cv.append(cross_val_score(bnb, data, target, cv=10))
    cv_mean.append(cv[i].mean())
    cv_std.append(cv[i].std())
    conf.append(confusion_matrix(target, y_pred))
    
    correct.append((target == y_pred).sum())
    wrong.append((target != y_pred).sum())
    

['excellent', 'awesome', 'love', 'loves', 'nice', 'recommend', 'must have', 'nice', 'beautiful', 'super', 'best']
['love', 'loves', 'nice', 'recommend', 'must have', 'nice', 'beautiful', 'super', 'best']
['nice', 'recommend', 'must have', 'nice', 'beautiful', 'super', 'best']
['must have', 'nice', 'beautiful', 'super', 'best']
['beautiful', 'super', 'best']


In [58]:
cv

[array([0.61, 0.57, 0.57, 0.55, 0.56, 0.54, 0.55, 0.59, 0.57, 0.53]),
 array([0.59, 0.57, 0.57, 0.54, 0.55, 0.53, 0.54, 0.58, 0.56, 0.53]),
 array([0.56, 0.55, 0.54, 0.53, 0.54, 0.51, 0.52, 0.57, 0.54, 0.52]),
 array([0.54, 0.55, 0.53, 0.53, 0.52, 0.51, 0.51, 0.55, 0.52, 0.51]),
 array([0.52, 0.51, 0.52, 0.51, 0.52, 0.5 , 0.5 , 0.54, 0.52, 0.51])]

In [51]:
cv_mean

[0.5640000000000001, 0.5559999999999999, 0.538, 0.5269999999999999, 0.515]

In [52]:
cv_std

[0.022449944320643626,
 0.02009975124224175,
 0.017776388834631174,
 0.014866068747318517,
 0.011180339887498959]

In [73]:
keywords = ['good', 'great', 'excellent', 'awesome','love', 'loves', 'nice','recommend', 'must have','nice']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    reviews[str(key)] = reviews.review.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

data = reviews[keywords]
target = reviews['sentiment']
bnb.fit(data, target)
y_pred = bnb.predict(data)
temp = cross_val_score(bnb, data, target, cv=10)
cv.append(temp)
cv_mean.append(cv[i].mean())
cv_std.append(cv[i].std())
conf.append(confusion_matrix(target, y_pred))
correct.append((target == y_pred).sum())
wrong.append((target != y_pred).sum())

In [77]:
keywords = ['good', 'great', 'excellent']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    reviews[str(key)] = reviews.review.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

data = reviews[keywords]
target = reviews['sentiment']
bnb.fit(data, target)
y_pred = bnb.predict(data)
temp = cross_val_score(bnb, data, target, cv=10)
cv.append(temp)
cv_mean.append(cv[i].mean())
cv_std.append(cv[i].std())
conf.append(confusion_matrix(target, y_pred))
correct.append((target == y_pred).sum())
wrong.append((target != y_pred).sum())

In [80]:
keywords = ['good', 'great', 'excellent', 'awesome','love']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    reviews[str(key)] = reviews.review.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

data = reviews[keywords]
target = reviews['sentiment']
bnb.fit(data, target)
y_pred = bnb.predict(data)
temp = cross_val_score(bnb, data, target, cv=10)
cv.append(temp)
cv_mean.append(cv[i].mean())
cv_std.append(cv[i].std())
conf.append(confusion_matrix(target, y_pred))
correct.append((target == y_pred).sum())
wrong.append((target != y_pred).sum())

In [82]:
keywords = ['good', 'excellent', 'love']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    reviews[str(key)] = reviews.review.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

data = reviews[keywords]
target = reviews['sentiment']
bnb.fit(data, target)
y_pred = bnb.predict(data)
temp = cross_val_score(bnb, data, target, cv=10)
cv.append(temp)
cv_mean.append(cv[i].mean())
cv_std.append(cv[i].std())
conf.append(confusion_matrix(target, y_pred))
correct.append((target == y_pred).sum())
wrong.append((target != y_pred).sum())

In [84]:
keywords = ['good', 'great', 'excellent', 'love']

for key in keywords:
    # Note that we add spaces around the key so that we're getting the word,
    # not just pattern matching.
    reviews[str(key)] = reviews.review.str.contains(
        ' ' + str(key) + ' ',
        case=False
    )

data = reviews[keywords]
target = reviews['sentiment']
bnb.fit(data, target)
y_pred = bnb.predict(data)
temp = cross_val_score(bnb, data, target, cv=10)
cv.append(temp)
cv_mean.append(cv[i].mean())
cv_std.append(cv[i].std())
conf.append(confusion_matrix(target, y_pred))
correct.append((target == y_pred).sum())
wrong.append((target != y_pred).sum())

In [85]:
correct

[567, 557, 539, 528, 516, 600, 564, 580, 547, 578]

In [86]:
wrong

[433, 443, 461, 472, 484, 400, 436, 420, 453, 422]

Do any of your classifiers seem to overfit? 
None of the classifiers seem to overfit

Which seem to perform the best? Why? 
Removing 'beautiful', 'super', and 'best' seemed to have the biggest impact on the number of correctly classified reviews

Which features seemed to be most impactful to performance? 
'awesome', 'good', 'great', and love 