In [1]:
# Import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import timeit


#Name of file
csvfilename = 'creditcard.csv'

In [13]:
# Import the dataset
df = pd.read_csv(csvfilename)
Data =  df.iloc[:, 1:20].values
target = df['Class']

from sklearn.model_selection import train_test_split, cross_val_score
X_train, X_test, y_train, y_test = train_test_split(Data, target, test_size = 0.2, random_state = 0)

In [14]:
# Random Forest
from sklearn import ensemble
start = timeit.timeit()

rfc = ensemble.RandomForestClassifier()
cv_scores_rfc=cross_val_score(rfc, X_train, y_train, cv=10)
end = timeit.timeit()
time_RFC = end - start
time_RFC

C:\Users\Julia2\Anaconda3-2\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Julia2\Anaconda3-2\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Julia2\Anaconda3-2\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Julia2\Anaconda3-2\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
C:\Users\Julia2\Anaconda3-2\lib\site-packages\sklearn\ensemble\f

-0.0006865000000289001

In [15]:
cv_scores_rfc

array([0.99947336, 0.99956111, 0.99921001, 0.99964889, 0.9995611 ,
       0.99960499, 0.99951721, 0.99942942, 0.9995611 , 0.99934164])

In [17]:
rfc.fit(X_train,y_train)
y_pred_rfc = rfc.predict(X_test)

C:\Users\Julia2\Anaconda3-2\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [20]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test,y_pred_rfc)
cm

array([[56855,     6],
       [   20,    81]], dtype=int64)

In [21]:
# Decision Tree
from sklearn import tree

start = timeit.timeit()

decision_tree = tree.DecisionTreeClassifier(
    criterion='entropy',
    max_features=1,
    max_depth=4,
    random_state = 1337
)

cv_scores_dectree = cross_val_score(decision_tree, X_train, y_train, cv=10)
end = timeit.timeit()
time_dectree = end - start
time_dectree

0.00010819999988598283

In [24]:
cv_scores_dectree

array([0.99863952, 0.99859557, 0.99833224, 0.99916612, 0.99859551,
       0.99881496, 0.99881496, 0.99846383, 0.99872718, 0.99868329])

In [25]:
decision_tree.fit(X_train, y_train)
y_pred_dectree = decision_tree.predict(X_test)
cm_dectree = confusion_matrix(y_test,y_pred_dectree)
cm

array([[56855,     6],
       [   20,    81]], dtype=int64)

In [28]:
print("Random Forest Accuracy: %0.5f (+/- %0.4f)" % (cv_scores_rfc.mean(), cv_scores_rfc.std() * 2))
print("Decision Tree Accuracy: %0.5f (+/- %0.4f)" % (cv_scores_dectree.mean(), cv_scores_dectree.std() * 2))

Random Forest Accuracy: 0.99949 (+/- 0.0003)
Decision Tree Accuracy: 0.99868 (+/- 0.0004)
